image: registry.gitlab.com/mffd3s/nswi177/student:latest

# Generic rules: do not re-run anything when adding a tag
workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

stages:
  - tests

tests:
  script:
    - ./14/shellcheck.sh
    
# Fetch the most up-to-date definition from tests repository
include:
  - remote: 'https://gitlab.mff.cuni.cz/teaching/nswi177/2022/common/tests/-/raw/master/ci.yml'
