
tasks:
  image: registry.gitlab.com/mffd3s/nswi177/student:latest
  script:
    - ./bin/run_tests.sh tasks

quizzes:
  image: registry.gitlab.com/mffd3s/nswi177/student:latest
  script:
    - ./bin/run_tests.sh quizzes
